export const ADD_MOVIE_TO_WATCHILIST = "ADD_MOVIE_TO_WATCHILIST";
export const REMOVE_MOVIE_FROM_WATCHLIST = "REMOVE_MOVIE_FROM_WATCHLIST";
export const ADD_MOVIVE_TO_WATCHED = "ADD_MOVIVE_TO_WATCHED";
export const REMOVE_MOVIE_FROM_WATCHED = "REMOVE_MOVIE_FROM_WATCHED";
export const MOVE_TO_WATCHLIST = "MOVE_TO_WATCHLIST";

